### ISSUE TITLE
Assignment B-1 Feedback

### ISSUE THREAD

**Issue by albinagib** [stat545ubc-2021/SummaryStat#1]
Hi Aditi,

Excellent work on your Assignment B-1! Please see a few comments below that will help you improve your function for the next submission: 
- Tidy submission:  Clear README.md file, reproducible code, good use of a release. You should be suppressing the messages when loading libraries by adding `suppressPackageStartupMessages()` around your library commands.
- Ex 1: Clear and well-written function.
- Ex 2: Great documentation.
   - @title is not a roxygen2 tag, the title and description are usually written like this:
`#' This is the title.
#'
#' This is the description. (or you can use the @description tag)
#'
#' These are further details. (you can use @details tag)
#'
#' @param x description here`
- Ex 3: Great use of examples to illustrate your function.
- Ex 4: Great demonstration of `test_that()` function.

Overall, the function looks fantastic - keep up the great work! Please let me know if you have any questions. Grades will be posted soon on Canvas.

Best,
Albina

**Comment by aditi48n** [comment]
Hello Albina, 

Thank you for the detailed feedback. 

Best,
Aditi
